# Generated by Django 6.0.1 on 2026-02-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_classgroup_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='semester',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
    ]
