# Generated by Django 6.0.1 on 2026-02-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_classgroup_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.PositiveIntegerField(),
        ),
    ]
