# Generated by Django 6.0.1 on 2026-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_studentprofile_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(),
        ),
    ]
