# Generated by Django 6.0.1 on 2026-02-08 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancesession_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HOLIDAY', 'Holiday')], max_length=10)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.classgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'group', 'date')},
            },
        ),
    ]
