# Generated by Django 6.0.1 on 2026-03-26 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qr_code_file', models.ImageField(upload_to='qr_codes/')),
                ('expires_at', models.DateTimeField()),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.classgroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'date'), name='unique_qr_per_day')],
            },
        ),
    ]
